P_RUC_ENTIDAD_EMISORA=20131368152
P_COD_SERVICIO=3011
P_NOMBRE_ENTIDAD_EMISORA=MINISTERIO DE CULTURA
P_COD_APLICATIVO=10
P_EST_ENVIADO=E
P_FLG_ENVIO=N
P_FLG_ERROR_ENVIO=E
P_CFLGANU=S
#URL.TRAMITE.ANEXO = http://200.48.76.125/siotramite/pages/modulos/descargaAnexo/pdf_descargaAnexo.jsf
P_TIP_EMISION=02
P_COD_GRUPO=3
P_EST_DOC_EMI=0
P_EST_DOC_EMI_OBS=8
P_NU_CANDES=1
P_NU_DET_EXP=1
P_IN_BUSCA_TEXTO=1
P_EST_RECEPCION=R
P_EST_OBSERVADO=O
P_NU_DES=1
P_TI_DES=01
P_ES_ELI=0
P_ES_DOC_REC=0
P_ES_ENV_POR_TRA=0
P_TI_PROCESO=R
P_ES_PROCESO=5
P_DE_NAMEPC=IOTRAMITE
P_CO_MOT=0
P_DOC_ESTADO_MSJ0=0
P_DOC_ESTADO_MSJ1=1
P_DOC_ESTADO_MSJ2=2
P_COD_ORI_ING=08
P_ES_DOC_EMI1=2
P_ES_DOC_EMI2=5
P_ES_DOC_EMI3=0
P_TI_ENV_MSJ1=NULL
P_PC = S
P_UPLOAD_DIRECTORY = tmppcm
P_TEMP_DIRECTORY=runtime-java
#P_PC=N
#P_TEMP_DIRECTORY=glassfish
#P_UPLOAD_DIRECTORY=tmppcm
P_MAX_FILE_SIZE=5242880
P_CLIENT_ID=MjU2NTI0Mjk5MTk4NzkxODg=
P_CLIENT_SECRET=MjU2NTI0Mjk5MTk4NzkxODk=
P_IP_CUO=127.0.0.1
P_ESTADO_MESA_VIRTUAL=ESTADO_MESA_VIRTUAL

