perfil=/util/images/icon/perfil.jpg
perfil2=/util/images/icon/Of_232-2016-ITP_SG.pdf
logo=/util/images/logo/
principal=/util/images/principal/
temp=/util/archivos/Doc2.pdf
#documentos = G://documentos//
documentos=documentos
icon=/util/images/icon
css=/util/css

