#CONFIGURACION DE SERVIDOR DE CORREOS
USER_NAME=sgd
USER_PASSWORD=DDDSDDDDFDFDSFSDFDFDFDB393
SERVER_IP=mail.pcm.gob.pe
SERVER_PORT=25
EMAIL_FROM=Notificaciones SGD<sgd@pcm.gob.pe>
SMTP_AUTH=false
SMTP_STARTTLS=true