#CONFIGURACION DEL PROGRAMADOR DE TAREAS
# 0(CERO MINUTOS) 0/2(CADA 2 MINUTOS) 8-20(DE 8 HORAS A 20 HORAS) *(DIA) *(MES) MON-FRI(DE LUNES A VIERNES)
timer.cron=0 0/5 08-23 * * MON-FRI
#timer.ws=0 0/30 08-20 * * MON-FRI
#timer.as_funcionario=0 1 00 * * MON-FRI
#timer.as_funcionario=0 1 00 * * *
#timer.fin_funcionario=0 1 00 * * *

#VERSION ONPE
timer.ws=0 0/30 08-20 * * MON-FRI
timer.as_funcionario=0 1 00 * * *
timer.fin_funcionario=0 1 00 * * *
timer.actualizar_ws_pide=0 0/1 08-20 * * MON-FRI